### PR TITLE
Update mkdocs-material to 7.1.0 (SOFTWARE-4584)

### PR DESCRIPTION
**Pull request by mtru32**

### CODE REVIEW

**Comment by brianhlin** [comment]
Hi @mtru32 the virtual school pages are particularly important since the school is starting in a few days. @osg-cat: I'm not expecting any differences between the two `mkdocs` versions that would affect the school pages (we've already updated https://opensciencegrid.org/docs/) but I will defer to you if you'd like to punt on this until after the school

**Comment by osg-cat** [comment]
Would it be possible to revert if things go badly?

**Comment by brianhlin** [comment]
Of course! And @mtru32 can verify that the existing pages look the same between the new version and what's in production (https://opensciencegrid.org/virtual-school-2021/)

**Comment by osg-cat** [comment]
Right, but we are on the cusp of starting to add the complex stuff — it’s not there yet. Let me at least get through the schedule tables today, as we discussed on Slack, and then think about it some more. This is a per-site change, right?

**Comment by brianhlin** [comment]
Yup, it's per site

**Review by brianhlin — APPROVED** [review]
Tim gave the 👍🏽 to move forward with this on Slack

**Pull request merged**
