### PR TITLE
Remove Code Copy + Add GPUs to Main Navigation

### PR DESCRIPTION
**Pull request by CannonLock**

### CODE REVIEW

**Review by osg-cat — COMMENTED** [review]
@rynge: Should it be “Containers and GPUs” or “GPUs and Containers”? We should pick one and use it consistently.

**Comment by CannonLock** [comment]
@osg-cat It looks like he had it as

**Comment by CannonLock** [comment]
My mistake, I misclicked on the close with comment button

**Comment by osg-cat** [comment]
@CannonLock, can you please resolve the merge conflicts that have arisen with this PR and then merge once you’re happy? We should whittle down the open PRs.

**Pull request merged**
